FROM registry.access.redhat.com/ubi9/python-311:1-77.1726664316
WORKDIR /graph-rag
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /graph-rag/requirements.txt
COPY rag_app.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "rag_app.py" ]